version: 2
jobs:
  build:
    docker:
      - image: cimg/node:16.14
    steps:
      - checkout
      - run: yarn
      - run: yarn pull:wkt
      - run: yarn build
      - run: yarn test
      - run: npx nyc report --reporter=text-lcov | npx coveralls
